### PR TITLE
add buildfarm.sh and docker files

### PR DESCRIPTION
**Pull request by pengbo0328**
pull request to pgpool-II buildfarm

### CODE REVIEW

**Comment by yugo-n** [comment]
Some comments..

> -FROM=buildfarm@your.hostname
> +FROM=buildfarm@pgpool.net

The default value of the variable (your.hostname) was intended to use in the host other than pgpool.net.
For now, this is working only in the pgpool, but when this is used in other host with the default value, the
reporting mails from pgpool.net domain would be delivered. So, I think, the default value  shouldn't be changed.

> +WORKDIR=$GITROOT/work

This variable is never used.

In addition, if docker-pgpool-II-regression is included in this repository, we should fix README
"2. Get docker-pgpool-II-regression from github" section. Or, this section could be removed.

**Comment by yugo-n** [comment]
> +ENV http_proxy http://www-proxy.sra.co.jp:80/
> This is our internal host name. Should be removed.

**Comment by pengbo0328** [comment]
change buildfarm.sh, README, Dockerfile with the above comments

**Comment by yugo-n** [comment]
During looking into the latest change, I found other points.

1.

> MAILTO=pgpool-hackers@pgpool.net
> REPLYTO=$MAILTO
> #FROM=buildfarm@your.hostname
> FROM=buildfarm@pgpool.net

The default values using pgpool.net are still left. I think these should be:

> MAILTO=pgpool-buildfarm@your.hostname
> FROM=buildfarm@your.hostname

2.

> NTP_SERVER=sranhm

This is since the initial commit, but  it also would be better to change the default value, like as:

> NTP_SERVER=your_ntp_server

3.
In README, the instruction to get scripts is described as:

> $ cd /var/buildfarm
> $ git clone https://github.com/pgpool/pgpool-II-buildfarm.git

If we follow this instruction, the following directories will be created:
- /var/buildfarm
- /var/buildfarm/pgpool-II-buildfarm
- /var/buildfarm/pgpool-II-buildfram/docker-pgpool-II-regression

However, in buildfarm.sh, GITROOT is defined as;

> SRCDIR=/var/buildfarm
> ...
> GITROOT=$SRCDIR/docker-pgpool-II-regression

The directory of $GITROOT(/var/buildfarm/docker-pgpool-II-regression) will never be created, and it will result in error.

It would be better to fix the instruction in README, or it might be better to fix the definition of variables to meet the new instruction.

4.
The new command option (-p) should be checked earlier at the initial part of the script, not in the loop of OS_LIST.

**Comment by yugo-n** [comment]
Thank you so much for a lot of fixes!
I think it is ready to merge the pull request.

**Comment by tatsuo-ishii** [comment]
Thank you Pengbo for providing patches! Thank you Yugo for extensive reviews!
I have just merged the patches.

**Pull request merged**
